### ISSUE TITLE
Segfault when used with tensorflow

### ISSUE THREAD

**Issue by juve** [kyamagu/faiss-wheels#1]
Thanks for working on these wheels. They are very useful.

On Debian Stretch with Python 3.6, I get a segfault if I try to import faiss before tensorflow, but not vice-versa.

This should reproduce the issue:
```
docker run --rm -it python:3.6-stretch bash
pip install faiss-cpu tensorflow
python -c "import faiss; import tensorflow" # segfaults
python -c "import tensorflow; import faiss" # works
```

The segfault only occurs with faiss-cpu, it does not occur with faiss-gpu.

**Comment by kyamagu** [comment]
@juve Thanks for reporting this. Likely conflict with a common dependency library (like glibc), where tensorflow is requiring newer version. `faiss-gpu` is distributed with manylinux2010 package and might be aligned with tensorflow's dependency, whereas `faiss-cpu` is manylinux1.

**Comment by kyamagu** [comment]
just uploaded manylinux2010 wheel packages for `faiss-cpu`
