### ISSUE TITLE
Move to 1.6.3?

### ISSUE THREAD

**Issue by biarne-a** [kyamagu/faiss-wheels#10]
It would be really nice if this pip package could install faiss 1.6.3 official version.
I would have liked to make a PR for this but I am not sure how to proceed.

**Comment by kyamagu** [comment]
Sure, will take a look

**Comment by kyamagu** [comment]
There is a bug in faiss v1.6.3 GPU build, needs a workaround specific to this commit. Perhaps use the newer untagged commit?
https://github.com/facebookresearch/faiss/issues/1159
