### ISSUE TITLE
Failed building wheel for faiss-cpu

### ISSUE THREAD

**Issue by ybshaw** [kyamagu/faiss-wheels#102]
**Describe the bug**
when use pip install faiss-cpu==1.7.2, some errors occured:  `Failed building wheel for faiss-cpu`

**To Reproduce**
Describe the steps to reproduce the behavior:

```
pip install faiss-cpu==1.7.2
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Linux
 - Architecture: x86_64
 - Python: 3.6.3
 - Version: 1.7.2

**Additional context**

**Comment by kyamagu** [comment]
Please attach a log, and also check the prerequisites
https://github.com/kyamagu/faiss-wheels?tab=readme-ov-file#building-source-package

**Comment by ybshaw** [comment]
> Please attach a log, and also check the prerequisites https://github.com/kyamagu/faiss-wheels?tab=readme-ov-file#building-source-package

I'm sorry, does this mean that the faiss-cpu library must be installed via source compilation, not directly pip installation?

**Comment by kyamagu** [comment]
If you intend to install it via source distribution, then yes.
