### ISSUE TITLE
Missing wheels for macos x86_64 for 1.8.0.post1

### ISSUE THREAD

**Issue by iXce** [kyamagu/faiss-wheels#109]
**Describe the bug**
PyPi had wheels for macos x86_64 for 1.8.0 (https://pypi.org/project/faiss-cpu/1.8.0/#files), but is missing them for 1.8.0.post1 (https://pypi.org/project/faiss-cpu/1.8.0.post1/#files)

**To Reproduce**
Try to install 1.8.0.post1 from an x86_64 macos machine

```
pip install faiss-cpu==1.8.0.post1
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Macos
 - Architecture: x86_64
 - Python: 3.8 and 3.10
 - Version: 1.8.0.post1

**Comment by kyamagu** [comment]
This seems to be due to the `macos-latest` runner being switched to the arm.
