### ISSUE TITLE
Importing faiss.swigfaiss leads to error

### ISSUE THREAD

**Issue by pritam-dey3** [kyamagu/faiss-wheels#111]
**Describe the bug**
I was trying to import faiss.swigfaiss.Index to static type index in my code. But it took me quite some painful hours to figure out the issue.

**To Reproduce**
The following code works.
```python
import faiss
# from faiss.swigfaiss import Index
import numpy as np


index = faiss.index_factory(16, "IDMap,Flat")
emb = np.random.uniform(0, 1, (8, 16)).astype(np.float32)

index.train(emb)
```
however, the following code fails
```python
import faiss
from faiss.swigfaiss import Index
import numpy as np


index = faiss.index_factory(16, "IDMap,Flat")
emb = np.random.uniform(0, 1, (8, 16)).astype(np.float32)

index.train(emb)
```
```
  File "<string>", line 9, in <module>
TypeError: IndexIDMap.train() missing 1 required positional argument: 'x'
```

In conda installation, both the above code works fine.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Architecture: x86_64
 - Python: 3.12.4
 - Version: 1.8.0

**Comment by kyamagu** [comment]
Hmm, this seems not to happen in the following:

```python
import faiss
from faiss.swigfaiss_avx2 import Index
import numpy as np


index = faiss.index_factory(16, "IDMap,Flat")
emb = np.random.uniform(0, 1, (8, 16)).astype(np.float32)
index.train(emb)
```

This indicates something is wrong when the optimization flag is not set

**Comment by kyamagu** [comment]
Btw, it is possible to import `Index` in the following way:

```python
import faiss
from faiss import Index
```

**Comment by pritam-dey3** [comment]
> Btw, it is possible to import `Index` in the following way:
> 
> ```python
> import faiss
> from faiss import Index
> ```

This solves my problem. Thanks
