### ISSUE TITLE
pip install faiss-cpu failed and version is 1.9.0 with python 3.13

### ISSUE THREAD

**Issue by SPKannan** [kyamagu/faiss-wheels#116]
**Describe the bug**
Tried to install FAISS-CPU lates version

**To Reproduce**
Describe the steps to reproduce the behavior:

```
pip install faiss-cpu
```

**Actiual behavior**
Failed to Install

Building wheels for collected packages: faiss-cpu
  Building wheel for faiss-cpu (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for faiss-cpu (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'faiss._swigfaiss' extension
      swigging faiss\faiss\python\swigfaiss.i to faiss\faiss\python\swigfaiss_wrap.cpp
      swig.exe -python -c++ -Doverride= -doxygen -Ifaiss -IC:\Users\Admin\AppData\Local\Temp\pip-build-env-fclyyio6\overlay\Lib\site-packages\numpy\_core\include -Ifaiss -I/usr/local\include -DSWIGWIN -o faiss\faiss\python\swigfaiss_wrap.cpp faiss\faiss\python\swigfaiss.i
      error: command 'swig.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for faiss-cpu
Failed to build faiss-cpu
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (faiss-cpu)
 

**Desktop (please complete the following information):**
 - OS: windows
 - Architecture: x86_64
 - Python: 3.13

**Additional context**

**Comment by kyamagu** [comment]
CPython 3.13 will be supported in the next maintenance release.
Meanwhile, please download wheels from the [CI artifacts](https://github.com/kyamagu/faiss-wheels/actions/runs/11606114456).
