### ISSUE TITLE
GPU package size limit

### ISSUE THREAD

**Issue by kyamagu** [kyamagu/faiss-wheels#34]
#33 seems to bring significant file size increase, causing pypi upload failure.
Needs to inspect the cause and find a workaround; perhaps by dropping some CUDA_ARCHITECTURE.

**Comment by kyamagu** [comment]
The following reduces the package size to 85M (<100M), but still exceeds 60M default.

- `CMAKE_CUDA_ARCHITECTURES="35-real;50-real;60-real;70-real;75"`
- `CUDAFLAGS=--compiler-options=-fvisibility=hidden,-fdata-sections,-ffunction-sections`

**Comment by rom1504** [comment]
you could consider asking for a size limit increase https://www.dampfkraft.com/code/distributing-large-files-with-pypi.html#get-a-size-limit-increase
https://github.com/pypa/pypi-support#guidelines-for-upload-limit-requests

**Comment by kyamagu** [comment]
@rom1504 Thanks, will make a request once the current optimized binary really exceeds the limit
