### ISSUE TITLE
Support M1 mac

### ISSUE THREAD

**Issue by kyamagu** [kyamagu/faiss-wheels#36]
It seems the following fix enables faiss build on ARM64 mac. Good to investigate further packaging issues.
https://github.com/facebookresearch/faiss/pull/1655

**Comment by kyamagu** [comment]
Actually, #47 still fails to build arm64 wheel on macOS. There needs to be CMAKE_OSX_ARCHITECTURES flag and corresponding dependencies for the target arch (libomp).

**Comment by kyamagu** [comment]
Fixed in #48

**Comment by ziyadmsq** [comment]
@kyamagu 
Many thanks for the support but is it fixed in all versions of python 3.7? i'm still having issues installing it though
maybe there's some kind of a workaround I'm not aware of?

Thanks

**Comment by kyamagu** [comment]
@ziyadmsq post the issue if you suspect any bug
