### ISSUE TITLE
ModuleNotFoundError: No module named 'faiss.swigfaiss_avx2'

### ISSUE THREAD

**Issue by nscozzaro** [kyamagu/faiss-wheels#39]
Hi, 

With faiss-cpu on linux I get an error:
```
Traceback:
env/lib/python3.6/site-packages/faiss/loader.py:31: in <module>
    from .swigfaiss_avx2 import *
E   ModuleNotFoundError: No module named 'faiss.swigfaiss_avx2'

During handling of the above exception, another exception occurred:
env/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
xxx/tests/handlers/xxx.py:6: in <module>
    from xxx.handlers import xxx as xxx_handler
xxx/handlers/xxx.py:2: in <module>
    import faiss
env/lib/python3.6/site-packages/faiss/__init__.py:17: in <module>
    from .loader import *
env/lib/python3.6/site-packages/faiss/loader.py:39: in <module>
    from .swigfaiss import *
env/lib/python3.6/site-packages/faiss/swigfaiss.py:13: in <module>
    from . import _swigfaiss
E   ImportError: dlopen: cannot load any more object with static TLS
```
Seems related to other issues, but I'm still not sure of the solution: 
https://github.com/facebookresearch/faiss/issues/866
https://github.com/facebookresearch/faiss/issues?q=is%3Aissue+swigfaiss_avx2

**Comment by kyamagu** [comment]
Could be a bad interaction with other imported packages. Try changing the import order in python

**Comment by MatejNikl** [comment]
I have a maybe a similar issue both linux and windows on versions `1.7.1` and `1.7.1.post1`:
```
INFO:faiss.loader:Loading faiss with AVX2 support.
INFO:faiss.loader:Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
```

On linux it proceeds with 
```
INFO:faiss.loader:Loading faiss.
INFO:faiss.loader:Successfully loaded faiss.
```
On windows the loading of faiss fails completely as discussed in #42.

**Comment by MatejNikl** [comment]
Hey, even though #44 mentions this issue as fixed, now I still get (both on windows and linux, python 3.9):
```
INFO:faiss.loader:Loading faiss with AVX2 support.
INFO:faiss.loader:Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
INFO:faiss.loader:Loading faiss.
INFO:faiss.loader:Successfully loaded faiss.
```
Is that an expected behavior?

**Comment by kyamagu** [comment]
Yes, avx2 extenstion is not included in the wheel for maximum
compatibility. You can safely ignore--
山口光太
（株）サイバーエージェント AI Lab
050-5305-9404
***@***.***

**Comment by yby9212** [comment]
try

```bash
cd your_python_path/site-packages/faiss
ln -s swigfaiss.py swigfaiss_avx2.py
```

**Comment by ckald** [comment]
> Yes, avx2 extenstion is not included in the wheel for maximum compatibility. You can safely ignore

Which basically means that faiss will run up to 10 times slower. A couple of years ago we discovered that our production server was not running faiss with AVX2 and had to work our way through debugging faiss and compiling specific avx2-enabled wheels: https://github.com/ckald/faiss-wheels-prophy/ (1.6.5)

I think that this **almost silent** behavior is very bad 🤷

**Comment by ckald** [comment]
@yby9212 your suggestion makes even worse -- you remove the error message and faiss still runs slowly. And nobody will know why

**Comment by kyamagu** [comment]
Feel free to make a PR if you wish to support both plain and avx2 extension in this repository.

You can always use [the official conda package](https://github.com/facebookresearch/faiss/blob/main/INSTALL.md). They are likely better optimized.

**Comment by zeaver** [comment]
see faiss install doc: https://github.com/facebookresearch/faiss/blob/main/INSTALL.md and the issue https://github.com/facebookresearch/faiss/issues/2872 . I meet the same problem when i install it via pip install. I uninstall faiss-gpu and re-install with conda again, it solve it. 

$$pip is not supported to install Faiss. Please use conda.$$

**Comment by eminmtas** [comment]
> try
> 
> ```shell
> cd your_python_path/site-packages/faiss
> ln -s swigfaiss.py swigfaiss_avx2.py
> ```

this works perfectly, thank you

**Comment by lfeges** [comment]
Windows Powershell
    cd your_python_path/site-packages/faiss
    New-Item -ItemType SymbolicLink -Path "swigfaiss_avx2.py" -Target "swigfaiss.py"

**Comment by ngbien83** [comment]
> Windows Powershell cd your_python_path/site-packages/faiss New-Item -ItemType SymbolicLink -Path "swigfaiss_avx2.py" -Target "swigfaiss.py"

Highly recommended for those who don't use Conda

**Comment by aleshem** [comment]
on windows, this did not work for me
The model returned NaNs
```
Windows Powershell
cd your_python_path/site-packages/faiss
New-Item -ItemType SymbolicLink -Path "swigfaiss_avx2.py" -Target "swigfaiss.py"
```
