### ISSUE TITLE
module 'faiss._swigfaiss' has no attribute 'delete_FloatVector'

### ISSUE THREAD

**Issue by robonetphy** [kyamagu/faiss-wheels#46]
On Google Colab:
1. following installation works fine:
`python3 -m pip install --upgrade faiss-gpu` 
2. But during import `import faiss` gives me the following error:
![image](https://user-images.githubusercontent.com/23169768/126879925-173772c1-3a2e-4ecc-9848-695506401467.png)
3.I downgraded  version and install
`python3 -m pip install --upgrade faiss-gpu==1.7.1` 
works fine for me

**Comment by kyamagu** [comment]
I cannot reproduce the above in colab. Did you install `faiss-cpu` beforehand?

```python
!pip install faiss-gpu
import faiss
```

**Comment by robonetphy** [comment]
Actually I used command as follow
`python3 -m pip install --upgrade faiss faiss-gpu`

**Comment by kyamagu** [comment]
Uninstall `faiss` package, which is not related to this repository

**Comment by robonetphy** [comment]
@kyamagu thanks it works for me
