### ISSUE TITLE
ImportError: DLL load failed while importing _swigfaiss: The specified module could not be found.

### ISSUE THREAD

**Issue by quickgrid** [kyamagu/faiss-wheels#53]
Hello, I am getting this error on windows 10 with python 3.9, faiss 1.7.2 after importing faiss. Same happens with conda-forge version.

**Comment by kyamagu** [comment]
This repository only concerns `faiss-cpu` and `faiss-gpu` packages on PyPI installation. Please go to the official repository for conda install. Also do not install other third-party wheel package (e.g., `faiss` without cpu or gpu in the package name)
