### ISSUE TITLE
pip installs the previous release when tries to build from source

### ISSUE THREAD

**Issue by mikhdm** [kyamagu/faiss-wheels#67]
When I'm trying to install faiss-cpu with `pip install --no-binary :all: faiss-cpu` pip installs 1.7.2 instead of 1.7.3, the latest one. Forcing installing `faiss-cpu==1.7.3` shows that 1.7.2 is the latest one and there is no 1.7.3 at all.

The problem live with publishing to PyPi, because there is nothing in Source Distributions block on the PyPi page of the library, see here: https://pypi.org/project/faiss-cpu/#files, that's why pip can't build from the source.

**Comment by mikhdm** [comment]
I see that the problem is fixed already, so can close it.

**Comment by kyamagu** [comment]
CI failure due to the [GPU package size limit](#34) prevented some package files from PyPI upload. A temporary workaround is a manual upload, or disabling the `faiss-gpu` package and triggering a release workflow.
