### ISSUE TITLE
AttributeError: 'MSVCCompiler' object has no attribute 'compiler' when trying to install faiss-cpu on Windows 11 and Python 3.8.10

### ISSUE THREAD

**Issue by Hevia** [kyamagu/faiss-wheels#69]
**Describe the bug**
When running Windows 11 and Python 3.8.10 attempting to install the latest version of faiss-cpu I get  **AttributeError: 'MSVCCompiler' object has no attribute 'compiler'**

**To Reproduce**
```
pip install faiss-cpu
```

**Expected behavior**
faiss-cpu should be installed just fine. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Architecture:  x86_64
 - Python: 3.18.10
 - Version: 1.7.3

**Additional context**
I can resolve the problem by installing a previous version
```
pip install faiss-cpu==1.7.2  
```
so it is not a blocker. I think I noticed on my other machine with Python 3.7 that faiss-cpu installed just fine without changing the version. I dont have it on hand to add any other details.

**Comment by kyamagu** [comment]
Can you post a complete log? Not sure if this is from a source package or a binary wheel.
