### ISSUE TITLE
faiss-cpu 1.7.4 not working with mkl 2023.1.0

### ISSUE THREAD

**Issue by softnado** [kyamagu/faiss-wheels#75]
**Describe the bug**
For environment with faiss-cpu 1.7.4 and mkl 2023.1.0, python import faiss attempt to load libmkl_intel_lp64.so.1 while only libmkl_intel_lp64.so.2 is installed.

**To Reproduce**
Describe the steps to reproduce the behavior:

Installation is from anaconda and using conda channels: defaults, pytorch, conda-forge

```bash
conda config --add channels defaults
conda config --add channels pytorch
conda config --add channels conda-forge
conda update conda

conda install faiss-cpu==1.7.4 mkl=2023.1.0
```
```python
import faiss
```

**Expected behavior**
Successful import

**Actual behavior**
```python
>>> import faiss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda/lib/python3.8/site-packages/faiss/__init__.py", line 16, in <module>
    from .loader import *
  File "/opt/miniconda/lib/python3.8/site-packages/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/opt/miniconda/lib/python3.8/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory
```

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Architecture: [e.g. x86_64]
 - Python: [e.g. 3.8]
 - Version: [e.g. v1.7.4]

**Additional context**
Discovered issue when use faiss-cpu and mkl under Azure Machine Learning environment.

**Comment by kyamagu** [comment]
Can you post an issue in [the official faiss repository](https://github.com/facebookresearch/faiss)? This repo is of the unofficial PyPI wheels.
