### ISSUE TITLE
inconsistent name: expected 'faiss-gpu', but metadata has 'faiss-cpu'

### ISSUE THREAD

**Issue by peterchanws** [kyamagu/faiss-wheels#77]
**Describe the bug**
Requested faiss-cpu from https://files.pythonhosted.org/packages/7d/00/b3aaad408a44e4f5d87ebfcd75d0b14eeaed9fe9bc7a9f5e185ff1d503d6/faiss-gpu-1.6.4.post2.tar.gz has inconsistent name: expected 'faiss-gpu', but metadata has 'faiss-cpu'

**To Reproduce**
Describe the steps to reproduce the behavior:
pip install faiss-gpu

**Desktop (please complete the following information):**
 - OS: macOS 12.6.6
 - Architecture: x86_64
 - Python: 3.11.3

**Comment by lelapin123** [comment]
Me too with python 3.10.11

**Comment by neeti865** [comment]
I am also facing the same issue. Anyone found a fix for this?

**Comment by johnurbanik** [comment]
Also seeing this on Ubuntu 20.04.6 LTS with Python 3.11.6

**Comment by kyamagu** [comment]
`faiss-gpu` is not supported anymore, and the source packages are removed from the PyPI. Please use the `faiss-cpu` source package to support GPUs.

**Comment by calypset** [comment]
If faiss-gpu is not supported anymore, is there any way to install faiss-cpu with cuda gpu support on windows? (sorry to open again with this question)

**Comment by calypset** [comment]
Thank you @kyamagu. Do you know if anyone try to build a source on windows with GPU support?
