### ISSUE TITLE
Support Selector for IDMap

### ISSUE THREAD

**Issue by vaaliferov** [kyamagu/faiss-wheels#81]
Hi, could you please update the python pip package with the changes in PR #2848 ?
https://github.com/facebookresearch/faiss/issues/2843
https://github.com/facebookresearch/faiss/pull/2848
https://github.com/facebookresearch/faiss/issues/2988

**Comment by vaaliferov** [comment]
Okay, thanks, I'll ask them.

**Comment by kyamagu** [comment]
Fixed #98
