### ISSUE TITLE
Release v1.7.4 on PyPI

### ISSUE THREAD

**Issue by yeoedward** [kyamagu/faiss-wheels#83]
The latest release of faiss-wheels is currently v1.7.4, but the latest release on PyPI is v1.7.2. This means that `faiss-gpu` cannot be used with python 3.11 at the moment, even though support was already added in v1.7.3. Any chance we can update PyPI? Happy to help if there is work involved.

**Comment by kyamagu** [comment]
We discontinue `faiss-gpu` due to the PyPI limitation, as noted in the [README.md](https://github.com/kyamagu/faiss-wheels#overview).
