### ISSUE TITLE
Not able to run gpu version on NVIDIA A100/A10

### ISSUE THREAD

**Issue by SandroChen** [kyamagu/faiss-wheels#97]
version:
faiss-gpu 1.7.2

file_content:
import faiss
gpu_res = faiss.StandardGpuResources()
index = faiss.GpuIndexFlatL2(gpu_res, d)

description:
After I run the code above, it stuck forever. The same code is workable on NVIDIA V100. Is there any solution? I saw your suggestion in #54 , but the archive seems gone and I cannot get any alternative one.

**Comment by kyamagu** [comment]
[We don't support GPU wheels anymore](https://github.com/kyamagu/faiss-wheels?tab=readme-ov-file#overview).

Wheels compatible with A100s are available on [the v1.7.3 release page](https://github.com/kyamagu/faiss-wheels/releases/tag/v1.7.3), but no support is planned in the future.

**Comment by SandroChen** [comment]
Thanks! It works perfectly.
